services:
  app-service:
    image: ryanycwdev/app-service # specify name of image on Docker Hub
    restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables
      DOMAIN: ${DOMAIN}
    expose:
      - "8000" # expose port internally to other containers only
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started
    networks:
      - app-network
      
  auth-service:
    image: ryanycwdev/auth-service
    restart: "always" # automatically restart container when server crashes
    environment:
      JWT_SECRET: ${JWT_SECRET}
      CORS_ALLOWED_ORIGINS: ${DOMAIN}
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    expose:
      - "3000" # expose port internally to other containers only
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    restart: "always"
    ports:
      - "80:80"   # HTTP port
      - "443:443" # HTTPS port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - app-service
      - auth-service
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    restart: "no"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge 

volumes:
  db:
    driver: local